[package]
name = "cfs-synapse"
version = "0.1.0"
edition = "2024"
description = "NASA cFS-friendly IDL and code generator for C headers and Rust repr(C) bindings"
repository = "https://github.com/sjbeskur/synapse"
readme = "../README.md"
license = "MIT OR Apache-2.0"
keywords = ["cfs", "nasa", "codegen", "idl", "embedded"]
categories = ["command-line-utilities", "development-tools::build-utils"]

[lib]
name = "cfs_synapse"
path = "src/lib.rs"

[[bin]]
name = "synapse"
path = "src/main.rs"

[dependencies]
synapse-parser      = { package = "cfs-synapse-parser", version = "0.1.0", path = "../synapse-parser" }
synapse-codegen-cfs = { package = "cfs-synapse-codegen-cfs", version = "0.1.0", path = "../synapse-codegen-cfs" }
clap                = { version = "4", features = ["derive"] }
pest                = "2"
