[workspace]
members = [
    "synapse-parser",
    "synapse-codegen-cfs",
    "synapse",
    "synapse-integration-tests",
    "examples/rust-canary",
    "cfs-sys",
]
default-members = [
    "synapse-parser",
    "synapse-codegen-cfs",
    "synapse",
    "synapse-integration-tests",
    "examples/rust-canary",
]
resolver = "2"

[workspace.package]
version = "0.2.0"
edition = "2024"
