[workspace]
members = [
    "synapse-parser",
    "synapse-codegen-cfs",
    "synapse",
    "synapse-integration-tests",
    "examples/rust-canary",
    "cfs-sys",
]
default-members = [
    "synapse-parser",
    "synapse-codegen-cfs",
    "synapse",
    "synapse-integration-tests",
    "examples/rust-canary",
]
resolver = "2"

[workspace.package]
version = "0.2.5"
edition = "2024"

[workspace.dependencies]
synapse-parser      = { package = "cfs-synapse-parser", version = "0.2.5", path = "synapse-parser" }
synapse-codegen-cfs = { package = "cfs-synapse-codegen-cfs", version = "0.2.5", path = "synapse-codegen-cfs" }
