[workspace]
members = [
    "synapse-parser",
    "synapse-codegen-cfs",
    "synapse",
    "synapse-integration-tests",
    "examples/rust-canary",
    "cfs-sys",
]
default-members = [
    "synapse-parser",
    "synapse-codegen-cfs",
    "synapse",
    "synapse-integration-tests",
    "examples/rust-canary",
]
resolver = "2"
