allow-branch = ["main", "release/*"]
consolidate-commits = true
dependent-version = "upgrade"
pre-release-commit-message = "chore: release {{version}}"
publish = false
push-remote = "origin"
tag-message = "Release {{version}}"
tag-name = "v{{version}}"
