[package]
name = "synapse-integration-tests"
version = "0.1.0"
edition = "2024"

[dev-dependencies]
synapse-parser      = { package = "cfs-synapse-parser", path = "../synapse-parser" }
synapse-codegen-cfs = { package = "cfs-synapse-codegen-cfs", path = "../synapse-codegen-cfs" }
cfs-synapse         = { path = "../synapse" }
