[package]
name = "synapse-integration-tests"
version.workspace = true
edition.workspace = true

[dev-dependencies]
synapse-parser      = { package = "cfs-synapse-parser", path = "../synapse-parser" }
synapse-codegen-cfs = { package = "cfs-synapse-codegen-cfs", path = "../synapse-codegen-cfs" }
cfs-synapse         = { path = "../synapse" }
trybuild           = "1"
