[package]
name = "cfs-synapse-parser"
version.workspace = true
edition.workspace = true
description = "Parser for the Synapse NASA cFS-friendly IDL"
repository = "https://github.com/sjbeskur/synapse"
readme = "../README.md"
license = "MIT OR Apache-2.0"
keywords = ["cfs", "nasa", "parser", "idl"]
categories = ["parser-implementations", "development-tools::build-utils"]

[lib]
name = "synapse_parser"
path = "src/lib.rs"

[dependencies]
pest = "2"
pest_derive = "2"
